services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - wiremock
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PROVIDER_URL: ${PROVIDER_URL}
      API_KEY: ${API_KEY}
    volumes:
      - ./app:/app        ##mounts the local code
      - ./tests:/app/tests     # <---for testing 
      - ./pytest.ini:/app/pytest.ini   # <--- Mount config file for test
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - transaction-network

  postgres: ##another service gonna be the database for persistance
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ##ports:
    ##  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transaction-network

  wiremock: ##The other service gonna be wiremock
    image: wiremock/wiremock:latest
    ##ports:
    ##  - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    command: ["--global-response-templating", "--port", "8080"]
    networks:
      - transaction-network

volumes:
  postgres_data:

networks:
  transaction-network:
    driver: bridge
